import type { NextPage } from "next";
import Head from "next/head";
import { BackgroundNoise } from "../components/BackgroundNoise";
import { Books } from "../components/Books";
import Stack from "../components/Stack";
import { Heading, Text } from "../components/Typography";
import { styled } from "../Stitches";
import { Location } from "../components/Location";
import { Page } from "../components/Page";

const Body = styled("body", {
  fontSize: 12,
  fontWeight: 600,
});

export const Padding = styled("div", {
  padding: "$2",
  variants: {
    size: {
      xs: { padding: "$1" },
      sm: { padding: "$2" },
      md: { padding: "$4" },
      lg: { padding: "$6" },
      xl: { padding: "$8" },
    },
  },
  defaultVariants: { size: "md" },
});

const shadowVariants = {
  shadow: {
    sm: { boxShadow: "$1" },
    md: { boxShadow: "$2" },
    lg: { boxShadow: "$3" },
  },
};

export const Panel = styled("div", {
  // background: "rgba(255, 255, 255, 0.1)",

  borderRadius: "$4",
  marginLeft: "auto",
  marginRight: "auto",

  padding: "$3",

  borderColor: "rgba(255, 255, 255, 0.6)",
  borderWidth: 1,
  borderStyle: "solid",

  variants: {
    ...shadowVariants,
  },
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Zaymon.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <BackgroundNoise />
        <Page>
          <Stack justify={"center"}>
            <Padding size="lg">
              <Heading size="hero">Zaymon Antonio</Heading>
            </Padding>
          </Stack>

          <Stack spacing="lg" direction="column">
            <Panel shadow="lg">
              <Padding size="lg">
                <Heading size="lg">This is me.</Heading>
                <Text>
                  Hey there. I{"'"}m a software engineer. I write programs. Do
                  you need help with a program? Why? Write your own damn
                  program. Jk this is filler text love you.
                </Text>
              </Padding>
            </Panel>

            <Location />

            <Books />
          </Stack>
        </Page>
      </Body>
    </>
  );
};

export default Home;
